name: blueripple-data-sets
version: '0.1.0.0'
synopsis: data-sets for Blue Ripple Politics along with Frames types and loaders for them
category: Numeric
author: Adam Conner-Sax
maintainer: adam@blueripplepolitics.org
copyright: 2019 Adam Conner-Sax
license: BSD3
github: blueripple/data-sets
extra-source-files:
- Changelog.md
- Readme.md
library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -O2
  - -fno-warn-unused-top-binds
  - -funbox-strict-fields
#  - -fplugin=Fusion.Plugin
  dependencies:
  - base >=4.12.0 && <4.14
  - containers >=0.5.0 && <0.7
  - directory >=1.3.3.0 && <1.4.0.0
  - exceptions >= 0.10.4 && < 0.11
  - foldl
#  - fusion-plugin
  - Frames-map-reduce
  - Frames
  - Frames-utils
  - knit-haskell
  - map-reduce-folds  
  - mtl
  - pandoc >= 2.9
  - pipes
  - polysemy >= 1.2
  - polysemy-zoo >= 0.7.0 && < 0.8
  - streamly >= 0.7.2 && < 0.8
  - text >=1.2.3 && <1.3
  - vinyl
data-dir: data
data-files:
- demographic/*.csv
- election/*.csv
- campaign-finance/*.csv
- dictionaries/*.csv
- geo/*.topojson
- other/*.csv